kind: ConfigMap
apiVersion: v1
metadata:
  name: name-of-your-configmap
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
   {
      "class": "AS3",
      "declaration": {
         "class": "ADC",
         "schemaVersion": "3.18.0",
         "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
         "label": "http",
         "remark": "A1 Template",
         "Nodeport": {
            "class": "Tenant",
            "profileSCTP": {
               "class": "Application",
               "template": "generic",
               "a1_80_vs": {
                     "class": "Service_SCTP",
                     "remark": "a1",
                     "virtualAddresses": [
                        "10.192.75.101"
                     ],
                     "virtualPort": 132,
                     "profileSCTP": {
                        "bigip": "/Common/sctp"
                     },
                     "pool": "sctp-pool"
               },
               "sctp-pool": {
                     "class": "Pool",
                    "monitors": [
                            "tcp"
                          ],                      
                     "members": [
                        {
                           "servicePort": 80,
                           "serverAddresses": []
                        }
                     ]
               }
            }
         }
      }
   }